# This file tells Render how to build and run your bot.
# It now uses a "web" service type to work with Render's free plan.

services:
  # This is now a "Web Service". It stays online because we run a dummy web server.
  - type: web
    name: udemy-coupon-bot
    # Use Python as the runtime environment
    env: python
    # Explicitly use the free plan
    plan: free
    # The command to install dependencies from requirements.txt
    buildCommand: "pip install -r requirements.txt"
    # The command to start the bot
    startCommand: "python udemy_scraper_bot.py"
    # Automatically deploy when you push new code to GitHub
    autoDeploy: yes

